NE_info:
  NE_map: {I I: I, I P: P I, I S: S I, P I: P I, P P: X, P S: X, S I: S I, S P: X,
    S S: X}
  NE_types: IPSUX
file:
  filePath_1GrammCSV: {path: /home/tbsexton/Documents/Projects/DiagnosticKB/MaintenanceLanguageProcessing/data/gs_data/vocab.csv}
  filePath_OriginalCSV:
    headers: [Description, Resolution]
    path: /home/tbsexton/Documents/Projects/DiagnosticKB/MaintenanceLanguageProcessing/data/gs_data/gs_data.csv
  filePath_nGrammCSV: {path: /home/tbsexton/Documents/Projects/DiagnosticKB/MaintenanceLanguageProcessing/data/gs_data/gs_data_nGram.csv}
value: {numberToken_show: '1000', similarityMatrix_alreadyChecked: 99, similarityMatrix_threshold: 50}
