file:
  filePath_OriginalCSV:
    path: C:/Users/sam11/Desktop/Git/mlp/app/taggingUI/csv/app_vocab.csv
    headers:
      - token
      - NE
  filePath_1GrammCSV:
    path: C:/Users/sam11/Desktop/Git/mlp/app/taggingUI/csv/app_vocab_mike.csv
  filePath_nGrammCSV:
    path: C:/Users/sam11/Desktop/Git/mlp/app/taggingUI/csv/app_vocab_mike.csv

value:
  numberToken_show: 1000
  similarityMatrix_threshold: 50